version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: guessing_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
