version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: databesa_name
      POSTGRES_USER: postgres_username
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
