import { Injectable } from '@angular/core';
import { BehaviorSubject } from "rxjs";

@Injectable({
  providedIn: 'root'
})
export class LanguageService {

  currentLanguage = new BehaviorSubject<string>('fi')
  public messageKey: string = '';

  private messages: { [key: string]: any } = {
    fi: {
      guideMessage: 'Arvaa numero väliltä 1-100',
      guesses: 'Arvaukset',
      startGame: 'Aloita peli',
      newGame: 'Uusi peli',
      placeGuess: 'Anna arvauksesi',
      guess: 'Arvaa',
      correctGuess: 'Oikein! Arvasit oikean numeron {attempts} yrityksellä',
      closeGuess: ' Lähellä!',
      lowGuess: 'Liian pieni! Valitse suurempi numero.',
      highGuess: 'Liian suuri! Valitse pienempi numero.',
      inputPlaceholder: 'Numero 1-100',
      isGuessed: 'On jo arvattu, valitse toinen',
      gameOverMessage: 'Peli on loppunut, aloita uusi peli',
      stats: 'Tilastot',
      totalCountOfGames: 'Pelien kokonaismäärä',
      averageGuesses: 'Arvausten keskiarvo',
      close: 'Sulje',
      winMessage: 'Voitit!',
      falseGuess: 'Numeron tulee olla välillä 1-100',
      clearAll: 'Poista kaikki',
      confirm: 'Vahvista',
      games: 'Pelit',
      secretNumber: 'Salainen numero',
      hide: 'Piilota',
    },
    en: {
      guideMessage: 'Guess a number between 1-100',
      guesses: 'guesses',
      startGame: 'Start Game',
      newGame: 'New game',
      placeGuess: 'Make your guess',
      guess: 'Guess',
      correctGuess: 'Correct! You guessed it with {attempts} attempts',
      closeGuess: ' Close!',
      lowGuess: 'Too low! Try a higher number.',
      highGuess: 'Too high! Try a lower number.',
      inputPlaceholder: 'Number 1-100',
      isGuessed: 'Already guessed, choose another',
      gameOverMessage: 'Game ended, start a new game',
      stats: 'Statistics',
      totalCountOfGames: 'Total count of games',
      averageGuesses: 'Average of guesses',
      close: 'Close',
      winMessage: 'You win!',
      falseGuess: 'Number must be between 1-100',
      clearAll: 'Clear all',
      confirm: 'Confirm',
      games: 'Games',
      secretNumber: 'Secret Number',
      hide: 'Hide',
    },
    no: {
      guideMessage: 'Gjett et tall mellom 1-100',
      guesses: 'Gjetninger',
      startGame: 'Start spill',
      newGame: 'Nytt spill',
      placeGuess: 'Gjett tallet ditt',
      guess: 'Gjett',
      correctGuess: 'Riktig! Du gjettet riktig med {attempts} forsøk',
      closeGuess: 'Nært!',
      lowGuess: 'For lavt! Prøv et høyere tall.',
      highGuess: 'For høyt! Prøv et lavere tall.',
      inputPlaceholder: 'Tall 1-100',
      isGuessed: 'Allerede gjettet, velg et annet',
      gameOverMessage: 'Spillet er over, start et nytt spill',
      stats: 'Statistikk',
      totalCountOfGames: 'Totalt antall spill',
      averageGuesses: 'Gjennomsnittlig antall gjetninger',
      close: 'Lukk',
      winMessage: 'Du vant!',
      falseGuess: 'Tallet må være mellom 1-100',
      clearAll: 'Tøm alt',
      confirm: 'Bekreft',
      games: 'Spill',
      secretNumber: 'Hemmelig tall',
      hide: 'Skjul',
    },
    es: {
      guideMessage: 'Adivina un número entre 1-100',
      guesses: 'Adivinanzas',
      startGame: 'Iniciar juego',
      newGame: 'Nuevo juego',
      placeGuess: 'Haz tu adivinanza',
      guess: 'Adivinar',
      correctGuess: '¡Correcto! Adivinaste con {attempts} intentos',
      closeGuess: '¡Cerca!',
      lowGuess: '¡Demasiado bajo! Intenta un número más alto.',
      highGuess: '¡Demasiado alto! Intenta un número más bajo.',
      inputPlaceholder: 'Número 1-100',
      isGuessed: 'Ya adivinado, elige otro',
      gameOverMessage: 'El juego ha terminado, inicia un nuevo juego',
      stats: 'Estadísticas',
      totalCountOfGames: 'Número total de juegos',
      averageGuesses: 'Promedio de adivinanzas',
      close: 'Cerrar',
      winMessage: '¡Ganaste!',
      falseGuess: 'El número debe estar entre 1-100',
      clearAll: 'Borrar todo',
      confirm: 'Confirmar',
      games: 'Juegos',
      secretNumber: 'Número secreto',
      hide: 'Ocultar',
    },
    el: {
      guideMessage: 'Μάντεψε έναν αριθμό μεταξύ 1-100',
      guesses: 'Μαντεψιές',
      startGame: 'Έναρξη παιχνιδιού',
      newGame: 'Νέο παιχνίδι',
      placeGuess: 'Κάνε την μαντεψιά σου',
      guess: 'Μάντεψε',
      correctGuess: 'Σωστό! Το μάντεψες με {attempts} προσπάθειες',
      closeGuess: 'Κοντά!',
      lowGuess: 'Πολύ χαμηλά! Δοκίμασε έναν μεγαλύτερο αριθμό.',
      highGuess: 'Πολύ ψηλά! Δοκίμασε έναν μικρότερο αριθμό.',
      inputPlaceholder: 'Αριθμός 1-100',
      isGuessed: 'Έχει ήδη μαντευτεί, διάλεξε άλλο',
      gameOverMessage: 'Το παιχνίδι τελείωσε, ξεκίνα ένα νέο παιχνίδι',
      stats: 'Στατιστικά',
      totalCountOfGames: 'Συνολικός αριθμός παιχνιδιών',
      averageGuesses: 'Μέσος όρος μαντεψιών',
      close: 'Κλείσιμο',
      winMessage: 'Κέρδισες!',
      falseGuess: 'Ο αριθμός πρέπει να είναι μεταξύ 1-100',
      clearAll: 'Διαγραφή όλων',
      confirm: 'Επιβεβαίωση',
      games: 'Παιχνίδια',
      secretNumber: 'Μυστικός αριθμός',
      hide: 'Απόκρυψη',
    },
    ee: {
      guideMessage: 'Arva ära number vahemikus 1-100',
      guesses: 'Arvamised',
      startGame: 'Alusta mängu',
      newGame: 'Uus mäng',
      placeGuess: 'Tee oma arvamus',
      guess: 'Arva',
      correctGuess: 'Õige! Arvasid ära {attempts} katsega',
      closeGuess: 'Lähedal!',
      lowGuess: 'Liiga madal! Proovi suuremat numbrit.',
      highGuess: 'Liiga kõrge! Proovi väiksemat numbrit.',
      inputPlaceholder: 'Number 1-100',
      isGuessed: 'Juba arvatud, vali teine',
      gameOverMessage: 'Mäng on lõppenud, alusta uut mängu',
      stats: 'Statistika',
      totalCountOfGames: 'Mängude koguarv',
      averageGuesses: 'Keskmine arvamusarv',
      close: 'Sulge',
      winMessage: 'Sa võitsid!',
      falseGuess: 'Number peab olema vahemikus 1-100',
      clearAll: 'Kustuta kõik',
      confirm: 'Kinnita',
      games: 'Mängud',
      secretNumber: 'Salajane number',
      hide: 'Peida',
    },
    sv: {
      guideMessage: 'Gissa ett nummer mellan 1-100',
      guesses: 'Gissningar',
      startGame: 'Starta spel',
      newGame: 'Nytt spel',
      placeGuess: 'Gör din gissning',
      guess: 'Gissa',
      correctGuess: 'Rätt! Du gissade rätt med {attempts} försök',
      closeGuess: 'Nära!',
      lowGuess: 'För lågt! Prova ett högre nummer.',
      highGuess: 'För högt! Prova ett lägre nummer.',
      inputPlaceholder: 'Nummer 1-100',
      isGuessed: 'Redan gissat, välj ett annat',
      gameOverMessage: 'Spelet är över, starta ett nytt spel',
      stats: 'Statistik',
      totalCountOfGames: 'Totalt antal spel',
      averageGuesses: 'Genomsnittligt antal gissningar',
      close: 'Stäng',
      winMessage: 'Du vann!',
      falseGuess: 'Numret måste vara mellan 1-100',
      clearAll: 'Rensa alla',
      confirm: 'Bekräfta',
      games: 'Spel',
      secretNumber: 'Hemligt nummer',
      hide: 'Dölj',
    },
    id: {
      guideMessage: 'Tebak angka antara 1-100',
      guesses: 'Tebakan',
      startGame: 'Mulai permainan',
      newGame: 'Permainan baru',
      placeGuess: 'Masukkan tebakanmu',
      guess: 'Tebak',
      correctGuess: 'Benar! Kamu menebak dengan {attempts} percobaan',
      closeGuess: 'Dekat!',
      lowGuess: 'Terlalu rendah! Coba angka yang lebih besar.',
      highGuess: 'Terlalu tinggi! Coba angka yang lebih kecil.',
      inputPlaceholder: 'Angka 1-100',
      isGuessed: 'Sudah ditebak, pilih yang lain',
      gameOverMessage: 'Permainan selesai, mulai permainan baru',
      stats: 'Statistik',
      totalCountOfGames: 'Jumlah total permainan',
      averageGuesses: 'Rata-rata tebakan',
      close: 'Tutup',
      winMessage: 'Kamu menang!',
      falseGuess: 'Angka harus antara 1-100',
      clearAll: 'Bersihkan semua',
      confirm: 'Konfirmasi',
      games: 'Permainan',
      secretNumber: 'Angka rahasia',
      hide: 'Sembunyikan',
    },
    fr: {
      guideMessage: 'Devinez un nombre entre 1 et 100',
      guesses: 'Suppositions',
      startGame: 'Démarrer le jeu',
      newGame: 'Nouveau jeu',
      placeGuess: 'Faites votre supposition',
      guess: 'Deviner',
      correctGuess: 'Correct! Vous avez deviné en {attempts} tentatives',
      closeGuess: 'Près!',
      lowGuess: 'Trop bas! Essayez un nombre plus élevé.',
      highGuess: 'Trop haut! Essayez un nombre plus bas.',
      inputPlaceholder: 'Nombre 1-100',
      isGuessed: 'Déjà deviné, choisissez un autre',
      gameOverMessage: 'Le jeu est terminé, démarrez un nouveau jeu',
      stats: 'Statistiques',
      totalCountOfGames: 'Nombre total de jeux',
      averageGuesses: 'Moyenne des suppositions',
      close: 'Fermer',
      winMessage: 'Vous avez gagné!',
      falseGuess: 'Le nombre doit être compris entre 1 et 100',
      clearAll: 'Tout effacer',
      confirm: 'Confirmer',
      games: 'Jeux',
      secretNumber: 'Numéro secret',
      hide: 'Cacher',
    },
    de: {
      guideMessage: 'Rate eine Zahl zwischen 1 und 100',
      guesses: 'Vermutungen',
      startGame: 'Spiel starten',
      newGame: 'Neues Spiel',
      placeGuess: 'Gib deine Vermutung ab',
      guess: 'Raten',
      correctGuess: 'Richtig! Du hast es in {attempts} Versuchen erraten',
      closeGuess: 'Nah dran!',
      lowGuess: 'Zu niedrig! Versuche eine höhere Zahl.',
      highGuess: 'Zu hoch! Versuche eine niedrigere Zahl.',
      inputPlaceholder: 'Zahl 1-100',
      isGuessed: 'Bereits geraten, wähle eine andere',
      gameOverMessage: 'Das Spiel ist vorbei, starte ein neues Spiel',
      stats: 'Statistiken',
      totalCountOfGames: 'Gesamtzahl der Spiele',
      averageGuesses: 'Durchschnittliche Vermutungen',
      close: 'Schließen',
      winMessage: 'Du hast gewonnen!',
      falseGuess: 'Die Zahl muss zwischen 1 und 100 liegen',
      clearAll: 'Alles löschen',
      confirm: 'Bestätigen',
      games: 'Spiele',
      secretNumber: 'Geheime Zahl',
      hide: 'Verbergen',
    },
    pl: {
      guideMessage: 'Zgadnij liczbę między 1 a 100',
      guesses: 'Próby',
      startGame: 'Rozpocznij grę',
      newGame: 'Nowa gra',
      placeGuess: 'Podaj swoją liczbę',
      guess: 'Zgadnij',
      correctGuess: 'Poprawnie! Zgadłeś za {attempts} prób',
      closeGuess: 'Blisko!',
      lowGuess: 'Za mało! Spróbuj większą liczbę.',
      highGuess: 'Za dużo! Spróbuj mniejszą liczbę.',
      inputPlaceholder: 'Liczba 1-100',
      isGuessed: 'Już zgadnięto, wybierz inną',
      gameOverMessage: 'Gra zakończona, zacznij nową grę',
      stats: 'Statystyki',
      totalCountOfGames: 'Całkowita liczba gier',
      averageGuesses: 'Średnia liczba prób',
      close: 'Zamknij',
      winMessage: 'Wygrałeś!',
      falseGuess: 'Liczba musi być między 1 a 100',
      clearAll: 'Wyczyść wszystko',
      confirm: 'Potwierdź',
      games: 'Gry',
      secretNumber: 'Tajny numer',
      hide: 'Ukryj',
    },
    lt: {
      guideMessage: 'Atspėkite skaičių tarp 1 ir 100',
      guesses: 'Spėjimai',
      startGame: 'Pradėti žaidimą',
      newGame: 'Naujas žaidimas',
      placeGuess: 'Padarykite savo spėjimą',
      guess: 'Spėk',
      correctGuess: 'Teisingai! Atspėjote per {attempts} bandymus',
      closeGuess: 'Artėjate!',
      lowGuess: 'Per mažai! Bandykite didesnį skaičių.',
      highGuess: 'Per daug! Bandykite mažesnį skaičių.',
      inputPlaceholder: 'Skaičius nuo 1 iki 100',
      isGuessed: 'Jau spėta, pasirinkite kitą',
      gameOverMessage: 'Žaidimas baigtas, pradėkite naują žaidimą',
      stats: 'Statistika',
      totalCountOfGames: 'Iš viso žaidimų',
      averageGuesses: 'Vidutinis spėjimų skaičius',
      close: 'Uždaryti',
      winMessage: 'Jūs laimėjote!',
      falseGuess: 'Skaičius turi būti tarp 1 ir 100',
      clearAll: 'Išvalyti viską',
      confirm: 'Patvirtinti',
      games: 'Žaidimai',
      secretNumber: 'Slaptas skaičius',
      hide: 'Paslėpti',
    },
    zh: {
      guideMessage: '猜一个1到100之间的数字',
      guesses: '猜测',
      startGame: '开始游戏',
      newGame: '新游戏',
      placeGuess: '输入你的猜测',
      guess: '猜',
      correctGuess: '正确！你用了{attempts}次猜对了',
      closeGuess: '很接近！',
      lowGuess: '太低了！试试更大的数字。',
      highGuess: '太高了！试试更小的数字。',
      inputPlaceholder: '数字 1-100',
      isGuessed: '已经猜过了，选择另一个',
      gameOverMessage: '游戏结束，开始新游戏',
      stats: '统计',
      totalCountOfGames: '总游戏次数',
      averageGuesses: '平均猜测次数',
      close: '关闭',
      winMessage: '你赢了！',
      falseGuess: '数字必须在1到100之间',
      clearAll: '清除所有',
      confirm: '确认',
      games: '游戏',
      secretNumber: '秘密数字',
      hide: '隐藏',
    },
    ja: {
      guideMessage: '1から100の間の数字を当ててください',
      guesses: '推測',
      startGame: 'ゲームを開始',
      newGame: '新しいゲーム',
      placeGuess: '推測を入力してください',
      guess: '推測する',
      correctGuess: '正解！{attempts}回の試行で当てました',
      closeGuess: '惜しい！',
      lowGuess: '低すぎます！もっと大きな数字を試してください。',
      highGuess: '高すぎます！もっと小さな数字を試してください。',
      inputPlaceholder: '1から100の数字',
      isGuessed: 'すでに推測されています、別のを選んでください',
      gameOverMessage: 'ゲームが終了しました。新しいゲームを始めましょう',
      stats: '統計',
      totalCountOfGames: 'ゲームの総数',
      averageGuesses: '推測の平均回数',
      close: '閉じる',
      winMessage: '勝ちました！',
      falseGuess: '数字は1から100の間でなければなりません',
      clearAll: 'すべてクリア',
      confirm: '確認',
      games: 'ゲーム',
      secretNumber: '秘密の数字',
      hide: '隠す',
    }
  };

  constructor() { }


  setLanguage(language: string) {
    if (this.messages[language]) {
      this.currentLanguage.next(language);
    } else {
      console.warn(`Language ${language} not supported`);
    }
  }

  getMessage(key: string, params: any = {}): string {
    const message = this.messages[this.currentLanguage.getValue()][key] || key;

    return message.replace(/{(\w+)}/g, (match: string, p1: string) => params[p1] || match);
  }
}
