import { Injectable } from '@angular/core';
import { BehaviorSubject } from "rxjs";

@Injectable({
  providedIn: 'root'
})
export class LanguageService {

  currentLanguage = new BehaviorSubject<string>('fi')
  public messageKey: string = '';

  private messages: { [key: string]: any } = {
    fi: {
      guideMessage: 'Arvaa numero väliltä 1-100',
      guesses: 'Arvaukset',
      startGame: 'Aloita peli',
      newGame: 'Uusi peli',
      placeGuess: 'Anna arvauksesi',
      guess: 'Arvaa',
      correctGuess: 'Oikein! Arvasit oikean numeron {attempts} yrityksellä',
      closeGuess: ' Lähellä!',
      lowGuess: 'Liian pieni! Valitse suurempi numero.',
      highGuess: 'Liian suuri! Valitse pienempi numero.',
      inputPlaceholder: 'Numero 1-100',
      isGuessed: 'On jo arvattu, valitse toinen',
      gameOverMessage: 'Peli on loppunut, aloita uusi peli',
      stats: 'Tilastot',
      totalCountOfGames: 'Pelien kokonaismäärä',
      averageGuesses: 'Arvausten keskiarvo',
      close: 'Sulje',
      winMessage: 'Voitit!',
      falseGuess: 'Numeron tulee olla välillä 1-100',
      clearAll: 'Poista kaikki',
      confirm: 'Vahvista',
      games: 'Pelit',
      secretNumber: 'Salainen numero',
      hide: 'Piilota',
      createNewUser: 'Luo uusi käyttäjä',
      login: 'Kirjaudu sisään',
      filterByUser: 'Rajaa käyttäjän mukaan',
      enterUserName: 'Syötä käyttäjänimi',
      username: 'Käyttäjänimi',
      password: 'Salasana',
      yes: 'Kyllä',
      no: 'Ei',
      logout: 'Kirjaudu ulos',
      newPassword: 'Uusi salasana',
      confirmNewPassword: 'Vahvista uusi salasana',
      loginSuccessful: 'Kirjautuminen onnistui',
      invalidCredentials: 'Virheelliset tunnukset',
      changePassword: 'Vaihda salasana',
      goToPlay: 'Siirry pelaamaan',
      created: 'luotiin',
      errorCreatingUser: 'Virhe käyttäjää luotaessa',
      cancel: 'Peruuta',
      passwordsDoNotMatch: 'Salasanat eivät täsmää',
      resetPassword: 'Nollaa salasana',
    },
    en: {
      guideMessage: 'Guess a number between 1-100',
      guesses: 'guesses',
      startGame: 'Start Game',
      newGame: 'New game',
      placeGuess: 'Make your guess',
      guess: 'Guess',
      correctGuess: 'Correct! You guessed it with {attempts} attempts',
      closeGuess: ' Close!',
      lowGuess: 'Too low! Try a higher number.',
      highGuess: 'Too high! Try a lower number.',
      inputPlaceholder: 'Number 1-100',
      isGuessed: 'Already guessed, choose another',
      gameOverMessage: 'Game ended, start a new game',
      stats: 'Statistics',
      totalCountOfGames: 'Total count of games',
      averageGuesses: 'Average of guesses',
      close: 'Close',
      winMessage: 'You win!',
      falseGuess: 'Number must be between 1-100',
      clearAll: 'Clear all',
      confirm: 'Confirm',
      games: 'Games',
      secretNumber: 'Secret Number',
      hide: 'Hide',
      createNewUser: 'Create new user',
      login: 'Log in',
      logout: 'Logout',
      filterByUser: 'Filter by user',
      enterUserName: 'Enter username',
      username: 'Username',
      password: 'Password',
      yes: 'Yes',
      no: 'No',
      newPassword: 'New password',
      confirmNewPassword: 'Confirm new password',
      loginSuccessful: 'Login successful',
      invalidCredentials: 'Invalid credentials',
      changePassword: 'Change password',
      goToPlay: 'Go to play',
      created: 'was created',
      errorCreatingUser: 'Error when creating user',
      cancel: 'Cancel',
      passwordsDoNotMatch: 'Passwords do not match',
      resetPassword: 'Reset password',
    },
    no: {
      guideMessage: 'Gjett et tall mellom 1-100',
      guesses: 'Gjetninger',
      startGame: 'Start spill',
      newGame: 'Nytt spill',
      placeGuess: 'Gjett tallet ditt',
      guess: 'Gjett',
      correctGuess: 'Riktig! Du gjettet riktig med {attempts} forsøk',
      closeGuess: 'Nært!',
      lowGuess: 'For lavt! Prøv et høyere tall.',
      highGuess: 'For høyt! Prøv et lavere tall.',
      inputPlaceholder: 'Tall 1-100',
      isGuessed: 'Allerede gjettet, velg et annet',
      gameOverMessage: 'Spillet er over, start et nytt spill',
      stats: 'Statistikk',
      totalCountOfGames: 'Totalt antall spill',
      averageGuesses: 'Gjennomsnittlig antall gjetninger',
      close: 'Lukk',
      winMessage: 'Du vant!',
      falseGuess: 'Tallet må være mellom 1-100',
      clearAll: 'Tøm alt',
      confirm: 'Bekreft',
      games: 'Spill',
      secretNumber: 'Hemmelig tall',
      hide: 'Skjul',
      createNewUser: 'Opprett ny bruker',
      login: 'Logg inn',
      filterByUser: 'Filtrer etter bruker',
      enterUserName: 'Skriv inn brukernavn',
      username: 'Brukernavn',
      password: 'Passord',
      yes: 'Ja',
      no: 'Nei',
      logout: 'Logg ut',
      newPassword: 'Nytt passord',
      confirmNewPassword: 'Bekreft nytt passord',
      loginSuccessful: 'Innlogging vellykket',
      invalidCredentials: 'Ugyldige legitimasjonsopplysninger',
      changePassword: 'Endre passord',
      goToPlay: 'Gå til spillet',
      created: 'ble opprettet',
      errorCreatingUser: 'Feil ved oppretting av bruker',
      cancel: 'Avbryt',
      passwordsDoNotMatch: 'Passordene stemmer ikke overens',
      resetPassword: 'Tilbakestill passord',
    },
    es: {
      guideMessage: 'Adivina un número entre 1-100',
      guesses: 'Adivinanzas',
      startGame: 'Iniciar juego',
      newGame: 'Nuevo juego',
      placeGuess: 'Haz tu adivinanza',
      guess: 'Adivinar',
      correctGuess: 'Correcto! Adivinaste con {attempts} intentos',
      closeGuess: 'Cerca!',
      lowGuess: 'Demasiado bajo! Intenta un número más alto',
      highGuess: 'Demasiado alto! Intenta un número más bajo',
      inputPlaceholder: 'Número 1-100',
      isGuessed: 'Ya adivinado, elige otro',
      gameOverMessage: 'El juego ha terminado, inicia un nuevo juego',
      stats: 'Estadísticas',
      totalCountOfGames: 'Número total de juegos',
      averageGuesses: 'Promedio de adivinanzas',
      close: 'Cerrar',
      winMessage: '¡Ganaste!',
      falseGuess: 'El número debe estar entre 1-100',
      clearAll: 'Borrar todo',
      confirm: 'Confirmar',
      games: 'Juegos',
      secretNumber: 'Número secreto',
      hide: 'Ocultar',
      createNewUser: 'Crear nuevo usuario',
      login: 'Iniciar sesión',
      filterByUser: 'Filtrar por usuario',
      enterUserName: 'Ingrese nombre de usuario',
      username: 'Nombre de usuario',
      password: 'Contraseña',
      yes: 'Sí',
      no: 'No',
      logout: 'Cerrar sesión',
      newPassword: 'Nueva contraseña',
      confirmNewPassword: 'Confirmar nueva contraseña',
      loginSuccessful: 'Inicio de sesión exitoso',
      invalidCredentials: 'Credenciales inválidas',
      changePassword: 'Cambiar contraseña',
      goToPlay: 'Ir a jugar',
      created: 'fue creado',
      errorCreatingUser: 'Error al crear usuario',
      cancel: 'Cancelar',
      passwordsDoNotMatch: 'Las contraseñas no coinciden',
      resetPassword: 'Restablecer contraseña',
    },
    ee: {
      guideMessage: 'Arva ära number vahemikus 1-100',
      guesses: 'Arvamised',
      startGame: 'Alusta mängu',
      newGame: 'Uus mäng',
      placeGuess: 'Tee oma arvamus',
      guess: 'Arva',
      correctGuess: 'Õige! Arvasid ära {attempts} katsega',
      closeGuess: 'Lähedal!',
      lowGuess: 'Liiga madal! Proovi suuremat numbrit.',
      highGuess: 'Liiga kõrge! Proovi väiksemat numbrit.',
      inputPlaceholder: 'Number 1-100',
      isGuessed: 'Juba arvatud, vali teine',
      gameOverMessage: 'Mäng on lõppenud, alusta uut mängu',
      stats: 'Statistika',
      totalCountOfGames: 'Mängude koguarv',
      averageGuesses: 'Keskmine arvamusarv',
      close: 'Sulge',
      winMessage: 'Sa võitsid!',
      falseGuess: 'Number peab olema vahemikus 1-100',
      clearAll: 'Kustuta kõik',
      confirm: 'Kinnita',
      games: 'Mängud',
      secretNumber: 'Salajane number',
      hide: 'Peida',
      createNewUser: 'Loo uus kasutaja',
      login: 'Logi sisse',
      filterByUser: 'Filtreeri kasutaja järgi',
      enterUserName: 'Sisestage kasutajanimi',
      username: 'Kasutajanimi',
      password: 'Parool',
      yes: 'Jah',
      no: 'Ei',
      logout: 'Logi välja',
      newPassword: 'Uus parool',
      confirmNewPassword: 'Kinnita uus parool',
      loginSuccessful: 'Sisselogimine õnnestus',
      invalidCredentials: 'Vale kasutajanimi või parool',
      changePassword: 'Muuda parool',
      goToPlay: 'Mine mängima',
      created: 'loodi',
      errorCreatingUser: 'Viga kasutaja loomisel',
      cancel: 'Tühista',
      passwordsDoNotMatch: 'Paroolid ei ühti',
      resetPassword: 'Lähtesta parool',
    },
    sv: {
      guideMessage: 'Gissa ett nummer mellan 1-100',
      guesses: 'Gissningar',
      startGame: 'Starta spel',
      newGame: 'Nytt spel',
      placeGuess: 'Gör din gissning',
      guess: 'Gissa',
      correctGuess: 'Rätt! Du gissade rätt med {attempts} försök',
      closeGuess: 'Nära!',
      lowGuess: 'För lågt! Prova ett högre nummer.',
      highGuess: 'För högt! Prova ett lägre nummer.',
      inputPlaceholder: 'Nummer 1-100',
      isGuessed: 'Redan gissat, välj ett annat',
      gameOverMessage: 'Spelet är över, starta ett nytt spel',
      stats: 'Statistik',
      totalCountOfGames: 'Totalt antal spel',
      averageGuesses: 'Genomsnittligt antal gissningar',
      close: 'Stäng',
      winMessage: 'Du vann!',
      falseGuess: 'Numret måste vara mellan 1-100',
      clearAll: 'Rensa alla',
      confirm: 'Bekräfta',
      games: 'Spel',
      secretNumber: 'Hemligt nummer',
      hide: 'Dölj',
      createNewUser: 'Skapa ny användare',
      login: 'Logga in',
      filterByUser: 'Filtrera efter användare',
      enterUserName: 'Ange användarnamn',
      username: 'Användarnamn',
      password: 'Lösenord',
      yes: 'Ja',
      no: 'Nej',
      logout: 'Logga ut',
      newPassword: 'Nytt lösenord',
      confirmNewPassword: 'Bekräfta nytt lösenord',
      loginSuccessful: 'Inloggning lyckad',
      invalidCredentials: 'Ogiltiga uppgifter',
      changePassword: 'Byt lösenord',
      goToPlay: 'Gå och spela',
      created: 'skapades',
      errorCreatingUser: 'Fel vid skapande av användare',
      cancel: 'Avbryt',
      passwordsDoNotMatch: 'Lösenorden matchar inte',
      resetPassword: 'Återställ lösenord',
    },
    fr: {
      guideMessage: 'Devinez un nombre entre 1 et 100',
      guesses: 'Suppositions',
      startGame: 'Démarrer le jeu',
      newGame: 'Nouveau jeu',
      placeGuess: 'Faites votre supposition',
      guess: 'Deviner',
      correctGuess: 'Correct! Vous avez deviné en {attempts} tentatives',
      closeGuess: 'Près!',
      lowGuess: 'Trop bas! Essayez un nombre plus élevé.',
      highGuess: 'Trop haut! Essayez un nombre plus bas.',
      inputPlaceholder: 'Nombre 1-100',
      isGuessed: 'Déjà deviné, choisissez un autre',
      gameOverMessage: 'Le jeu est terminé, démarrez un nouveau jeu',
      stats: 'Statistiques',
      totalCountOfGames: 'Nombre total de jeux',
      averageGuesses: 'Moyenne des suppositions',
      close: 'Fermer',
      winMessage: 'Vous avez gagné!',
      falseGuess: 'Le nombre doit être compris entre 1 et 100',
      clearAll: 'Tout effacer',
      confirm: 'Confirmer',
      games: 'Jeux',
      secretNumber: 'Numéro secret',
      hide: 'Cacher',
      createNewUser: 'Créer un nouvel utilisateur',
      login: 'Connexion',
      filterByUser: 'Filtrer par utilisateur',
      enterUserName: "Entrez le nom d'utilisateur",
      username: "Nom d'utilisateur",
      password: 'Mot de passe',
      yes: 'Oui',
      no: 'Non',
      logout: 'Déconnexion',
      newPassword: 'Nouveau mot de passe',
      confirmNewPassword: 'Confirmer le nouveau mot de passe',
      loginSuccessful: 'Connexion réussie',
      invalidCredentials: 'Identifiants invalides',
      changePassword: 'Changer le mot de passe',
      goToPlay: 'Aller jouer',
      created: 'a été créé',
      errorCreatingUser: 'Erreur lors de la création de l\'utilisateur',
      cancel: 'Annuler',
      passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
      resetPassword: 'Réinitialiser le mot de passe',
    },
    de: {
      guideMessage: 'Rate eine Zahl zwischen 1 und 100',
      guesses: 'Vermutungen',
      startGame: 'Spiel starten',
      newGame: 'Neues Spiel',
      placeGuess: 'Gib deine Vermutung ab',
      guess: 'Raten',
      correctGuess: 'Richtig! Du hast es in {attempts} Versuchen erraten',
      closeGuess: 'Nah dran!',
      lowGuess: 'Zu niedrig! Versuche eine höhere Zahl.',
      highGuess: 'Zu hoch! Versuche eine niedrigere Zahl.',
      inputPlaceholder: 'Zahl 1-100',
      isGuessed: 'Bereits geraten, wähle eine andere',
      gameOverMessage: 'Das Spiel ist vorbei, starte ein neues Spiel',
      stats: 'Statistiken',
      totalCountOfGames: 'Gesamtzahl der Spiele',
      averageGuesses: 'Durchschnittliche Vermutungen',
      close: 'Schließen',
      winMessage: 'Du hast gewonnen!',
      falseGuess: 'Die Zahl muss zwischen 1 und 100 liegen',
      clearAll: 'Alles löschen',
      confirm: 'Bestätigen',
      games: 'Spiele',
      secretNumber: 'Geheime Zahl',
      hide: 'Verbergen',
      createNewUser: 'Neuen Benutzer erstellen',
      login: 'Anmelden',
      filterByUser: 'Nach Benutzer filtern',
      enterUserName: 'Benutzernamen eingeben',
      username: 'Benutzername',
      password: 'Passwort',
      yes: 'Ja',
      no: 'Nein',
      logout: 'Abmelden',
      newPassword: 'Neues Passwort',
      confirmNewPassword: 'Neues Passwort bestätigen',
      loginSuccessful: 'Anmeldung erfolgreich',
      invalidCredentials: 'Ungültige Anmeldeinformationen',
      changePassword: 'Passwort ändern',
      goToPlay: 'Zum Spiel gehen',
      created: 'wurde erstellt',
      errorCreatingUser: 'Fehler beim Erstellen des Benutzers',
      cancel: 'Abbrechen',
      passwordsDoNotMatch: 'Die Passwörter stimmen nicht überein',
      resetPassword: 'Passwort zurücksetzen',
    },
  }
  constructor() {}


  setLanguage(language: string) {
    if (this.messages[language]) {
      this.currentLanguage.next(language);
    } else {
      console.warn(`Language ${language} not supported`);
    }
  }

  getMessage(key: string, params: any = {}): string {
    const message = this.messages[this.currentLanguage.getValue()][key] || key;

    return message.replace(/{(\w+)}/g, (match: string, p1: string) => params[p1] || match);
  }
}
